### PR TITLE
Update: exposes discovery websocket connection

### LINKED ISSUE #4: Expose discovery websocket connection
Hi @RangerMauve would you consider a (simple, I guess) PR that exposes the discovery websocket connection? 

This can be useful for observability purposes like checking on the websocket state.

### PR DESCRIPTION
**Pull request by dpaez**
This PR closes #4 

The idea is to expose the discovery websocket as another property. This subtle change allows it.

### CODE REVIEW

**Review by RangerMauve — APPROVED** [review]

**Comment by RangerMauve** [comment]
Awesome, thank you!

Would you be interested in being added as a collaborator to the repo?

**Comment by RangerMauve** [comment]
Out in 1.4.0

**Comment by dpaez** [comment]
> Would you be interested in being added as a collaborator to the repo?

Yeah, no prob. 👍

**Comment by RangerMauve** [comment]
What's your NPM username BTW?

**Pull request merged**
